services:
  laravel_monitoring:
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        AUTORUN_ENABLED: "false"
        APP_ENV: ${APP_ENV}
    container_name: ${APP_HOSTNAME}
    hostname: ${APP_HOSTNAME}
    environment:
      PUID: 1000
      SSL_MODE: 'mixed'
    volumes:
      - ./:/var/www/html
    ports:
      - '8080:80'
      - '8180:443'
    networks:
      - laravel_monitoring
    depends_on:
      - mysql
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost || exit 1"]
      interval: 5m
      timeout: 3s
      retries: 3
  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    networks:
      - laravel_monitoring
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s

networks:
  laravel_monitoring:
    driver: bridge
